---

apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gateway
  labels:
    domain: k8s-gateway.nginx.org
spec:
  gatewayClassName: bigip
  listeners:
  - name: http
    port: 80
    protocol: HTTP
  addresses:
    - value: 10.250.18.119

# ---

# apiVersion: gateway.networking.k8s.io/v1beta1
# kind: HTTPRoute
# metadata:
#   name: coffee
# spec:
#   parentRefs:
#   - name: gateway
#     sectionName: http
#   hostnames:
#   - "cafe.example.com"
#   rules:
#   - matches:
#     - path:
#         type: PathPrefix
#         value: /coffee
#     - path:
#         type: PathPrefix
#         value: /zongzw
#     backendRefs:
#     - name: coffee
#       port: 80

# ---

# apiVersion: gateway.networking.k8s.io/v1beta1
# kind: HTTPRoute
# metadata:
#   name: tea
# spec:
#   parentRefs:
#   - name: gateway
#     sectionName: http
#   hostnames:
#   - "cafe.example.com"
#   rules:
#   - matches:
#     - path:
#         type: PathPrefix
#         value: /tea
#     backendRefs:
#     - name: tea
#       port: 80
      