---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - gateways.f5.com
  resources:
  - adcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateways.f5.com
  resources:
  - adcs/finalizers
  verbs:
  - update
- apiGroups:
  - gateways.f5.com
  resources:
  - adcs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateways.f5.com
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateways.f5.com
  resources:
  - routes/finalizers
  verbs:
  - update
- apiGroups:
  - gateways.f5.com
  resources:
  - routes/status
  verbs:
  - get
  - patch
  - update
