
---

apiVersion: v1
kind: Namespace
metadata:
  name: abcd

---

apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: rg-tls
  namespace: abcd
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: default
  to:
    - group: ""
      kind: Secret
      # name: test-service
      
---

apiVersion: v1
kind: Secret
metadata:
  name: mytls
  namespace: abcd
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDiDCCAnACCQCwsetXAEnCoDANBgkqhkiG9w0BAQUFADCBhTELMAkGA1UEBhMC
    Q04xCzAJBgNVBAgMAkJKMRAwDgYDVQQHDAdiZWlqaW5nMQswCQYDVQQKDAJmNTEU
    MBIGA1UECwwLem9uZy5mNS5jb20xFjAUBgNVBAMMDWEuem9uZy5mNS5jb20xHDAa
    BgkqhkiG9w0BCQEWDWEuem9uZ0BmNS5jb20wHhcNMjExMjA3MDMwNjM3WhcNMjIw
    MTA2MDMwNjM3WjCBhTELMAkGA1UEBhMCQ04xCzAJBgNVBAgMAkJKMRAwDgYDVQQH
    DAdiZWlqaW5nMQswCQYDVQQKDAJmNTEUMBIGA1UECwwLem9uZy5mNS5jb20xFjAU
    BgNVBAMMDWEuem9uZy5mNS5jb20xHDAaBgkqhkiG9w0BCQEWDWEuem9uZ0BmNS5j
    b20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDgHLExdv8aok2MlQJn
    A7PI2+g/VUdAa2/cf7IkUtgv7XhDgk7OBcBw1ggNqAgLTqsY3o48aHUhAlQcLtSs
    h7XYxlbrdTLhiQc/DSqaf4yxlJ139RJ6qMlBBilkSCRtGBv7DUxGByxdweHr5Zwf
    qIGNw5f3lm5oF6htXL49sgYzUlljuiNhrq7eFZFBStUHNhobYUA8ZeOk/WyMDrup
    sb8VCLv/eAjxixNQeonlZC1DY/qpCATd/xYVOEyR6tDb41bXehmqbpFWnOumPEud
    zXI+O9q58tXfFTuUtGXP3xgaHaxSs9xk/Iqn5bpizlwIlLMSs/wVr/uCQbLMvAAL
    wvKbAgMBAAEwDQYJKoZIhvcNAQEFBQADggEBAMYEWzDtbjYlqOWtuaCUw2S3fJFB
    +IWwWVsu0LN6+a1OPIDpAb5/ueKGv4CNDi5bXLTSP2or4CsWpz4mzK0Zp3Gt12uG
    NeOI4IUOd+5c+X+eF8fuW42luXBXHsNZPT7HNFCVV2XmhtOE90TsR/qPVH4llDlJ
    K+aHk9dd/PCSgG6+S7wwQhUxLdM7prns6RmPbUT2Sr3r57jS3JJF56Ejk2/LLmNK
    XHPO+a5hOBuEcwpEtuBB64/uuY1z+5vLddFl/8snHbWAZEQdUD1k9Vo7XXmP/6ac
    fYc0k0zdhJcqg45ftWumTWuPBVxx78TdK6k5nN9+TDgB7gSnjCyu4JyAl0w=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEA4ByxMXb/GqJNjJUCZwOzyNvoP1VHQGtv3H+yJFLYL+14Q4JO
    zgXAcNYIDagIC06rGN6OPGh1IQJUHC7UrIe12MZW63Uy4YkHPw0qmn+MsZSdd/US
    eqjJQQYpZEgkbRgb+w1MRgcsXcHh6+WcH6iBjcOX95ZuaBeobVy+PbIGM1JZY7oj
    Ya6u3hWRQUrVBzYaG2FAPGXjpP1sjA67qbG/FQi7/3gI8YsTUHqJ5WQtQ2P6qQgE
    3f8WFThMkerQ2+NW13oZqm6RVpzrpjxLnc1yPjvaufLV3xU7lLRlz98YGh2sUrPc
    ZPyKp+W6Ys5cCJSzErP8Fa/7gkGyzLwAC8LymwIDAQABAoIBAA+5M51a0e8WcAZq
    9e4wTk7LTvISk5srbn+z3dW6kjxaltN1sv21XZkNCyeaIGZasJpgEu6eDYmxViFc
    D8PDCbkZwUNnx5gXOxDrZY/NXxueZ6Xg5dkBOo17VzAX96ZHyL7GYhGPs0cosScR
    xvBZrC08Cc9vGHPpJQH3PcmqUdEL1ml03ewray5BB/vHnydw2zNQy6iLOgHO4/Qj
    ax9Ua9M0zEb84u392gLZgY28R8HeyAVHnvSLYzHIammPswBJNQXMAgtuyqCpvgaE
    2eJoayVUhl1xANEknAYenEOc2Y9sZ28eUdM1UDdUSUF3DiEdU7LBEITGI1qkm8qs
    brwz2uECgYEA78LE9lh6Mb+CB3vfLRz+hxuKCsxBZO3agHPZxQlKEaGB6QHtw03h
    PG5gbPKpOzi1WmjLmffkGWCiLM6hZw3Qn43hH8iCqFzGSgfqaAq/DuT64+rlb7Fb
    d1avkQfTDRCHCzJSp7u0s4Lm874no3rMz6TgEo1eQJ//oBuaC+9BlSMCgYEA70qW
    j4aDeVoG4utp7wKaTvQJmOmwxM9cgT/+qhXoVkhmAP2ysprStKirvXMhFY4MZB31
    lYmp3gSrtzQxN+t1abrltPx8/9VnzAd/2u4gOrgIhnSrSHB1ODszIe+86tdeyz6R
    7PnysAYfXqdOcNVMr95AaQpXvGY2lFi0v9n+sCkCgYBqvcKkjgVwynrgTBSy5/ql
    Oex+HCts/LvPfkRQhW81ZDsK+nHZBn4lQlqphmszU27h3k/urz8c0TnCSwfucmcT
    8b1tQf5xaERbRyTjxw0CW40bFUOqM0KuYahuIBak9Vu572B/DoFHfhrGHz1UeeJe
    +19KwydYDCNpK4CsmYsQEwKBgGOtynIXMoVGfz/fmM07ZFQnTCgqkLwrNPmSUt8/
    KP1oQzV+eQX1gHhJGuFcKBf2iCrcYATex6f4gh9a2nXU26AjfrSZyOg5WXegWB42
    u646IzL/Pqp6ThoSbwZf+25IMPCxK9BvfizdIAwp3X8bG0rXZjVbXZjZazr4iLKy
    eGmhAoGAE9YIjHkB1aMP5zddrcs+GItHKI8xzZGWDQ3BNc2X4+7pQUH5pVmyFMDb
    xWP4MwVUBndW/y9E9HWSeYTSTYnQLIF0UgyzZq9VbRjOmmAPxndcSP1t+A3ti3MQ
    4VUbnnuHFdDNkCic6cu3B/DuxaKx1JybIPrRnnTc9SqkzbqBiT4=
    -----END RSA PRIVATE KEY-----