apiVersion: gateways.f5.com/v1
kind: Adc
metadata:
  labels:
    app.kubernetes.io/name: adc
    app.kubernetes.io/instance: adc-sample
    app.kubernetes.io/part-of: bigip-kubernetes-gateway
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: bigip-kubernetes-gateway
  name: adc-sample
spec:
  # TODO(user): Add fields here
  foo: zongzw
